# Site settings
title: Pudrink Bunda
email: artantyutami@gmail.com
description: Jual Pudrink Tulungagung
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pudrink.klikada.com" # the base hostname & protocol for your site e.g. http://yvesespinosa.com
download_button_url: "whatsapp://send?text=Hallo, !&phone=+6281335556312"

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
twitter_url:  

# Build settings
markdown: kramdown
